### ISSUE TITLE
The "video" key is a must in llava_next_video in json data?

### ISSUE THREAD

**Issue by Namzakku** [zjysteven/lmms-finetune#5]
I want to train llava_next_video on 2 different dataset together, 1 is video only and 1 is image only. 
I have set up the json in the below format:

```
    {
        "system_prompt": "Explain what you see in the follow frame.",
        "image": "4LAXV2KV.jpg",
        "conversations": [
            {
                "from": "human",
                "value": "<image>\nWhat can you see?"
            },
            {
                "from": "gpt",
                "value": "Sample"
            }
        ]
    },
    {
        "system_prompt": "Explain what you see in the follow frame.",
        "video": "AMVM7HR4.mp4",
        "conversations": [
            {
                "from": "human",
                "value": "<video>\nWhat can you see?"
            },
            {
                "from": "gpt",
                "value": "Sample"
            }
        ]
    },
```

and I got the below error:

```
Traceback (most recent call last):
  File "/workspace/lmms-finetune/train.py", line 157, in <module>
    train()
  File "/workspace/lmms-finetune/train.py", line 142, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1932, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2230, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/usr/local/lib/python3.10/dist-packages/accelerate/data_loader.py", line 454, in __iter__
    current_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 694, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/workspace/lmms-finetune/collators/llava_next_video.py", line 40, in __call__
    print(vision_inputs["pixel_values_videos"].shape)
KeyError: 'pixel_values_videos'
```

This also happened if I passed only the image dataset, so I think it will not work if there is no video in each of the data in the json.

**Comment by zjysteven** [comment]
There was a `print` call that should have been removed. Could you pull the latest codebase and try again? By changing the `TRAIN_DATA_PATH=./example_data/video.json` to `TRAIN_DATA_PATH=./example_data/single_image.json` in the `example.sh` I can successfully finish a training run.

**Comment by Namzakku** [comment]
oh so that is only the print problem! Thanks! I got it working!
btw when I conduct clean installation, I found that protobuf and wandb was missing. I think you can add it to requirements.txt. 

Great repo btw! Cheers!
