### ISSUE TITLE
AttributeError: 'ModulesToSaveWrapper' object has no attribute 'get_input_embeddings'

### ISSUE THREAD

**Issue by Kshitijpawar** [zjysteven/lmms-finetune#59]
I'm trying to train LLaVA-Next-Video with the vision encoder and vision projector but I'm getting the no atttribute error.
Below is the modified example_train_video.sh script and the output log

Training Script 
```
#!/bin/bash
# conda activate lmms-finetune
source /home/kshitijv/miniconda3/bin/activate lmms-finetune
cd /home/kshitijv/lmms/lmms-finetune

export CUDA_VISIBLE_DEVICES=0,1,2,3
export BNB_CUDA_VERSION=124
export LD_LIBRARY_PATH=/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/nvidia/nvjitlink/lib:$LD_LIBRARY_PATH
NUM_GPUS=4
DISTRIBUTED_ARGS="
    --nnodes=1 \
    --nproc_per_node ${NUM_GPUS} \
    --rdzv_backend c10d \
    --rdzv_endpoint localhost:0
"

# arguments that are very likely to be changed
# according to your own case
MODEL_ID=llava-next-video-7b                            # model id; pick on by running `python supported_models.py`
TRAIN_DATA_PATH=./example_data/edtok_train_ogndgemini.json   # path to the training data json file
EVAL_DATA_PATH=./example_data/edtok_test_ogndgemini.json     # path to the evaluation data json file (optional)
IMAGE_FOLDER=./example_data/images                      # path to the image root folder; if provided, the image paths in the json should be relative
VIDEO_FOLDER=./example_data/videos                      # path to the video root folder; if provided, the video paths in the json should be relative
NUM_FRAMES=8                                            # how many frames are sampled from each video

TRAIN_VISION_ENCODER=True                              # whether train the vision encoder
USE_VISION_LORA=True                                   # whether use lora for vision encoder (only effective when `TRAIN_VISION_ENCODER` is True)
TRAIN_VISION_PROJECTOR=True                            # whether train the vision projector (only full finetuning is supported)

USE_LORA=False                                           # whether use lora for llm
Q_LORA=False                                            # whether use q-lora for llm; only effective when `USE_LORA` is True
LORA_R=8                                                # the lora rank (both llm and vision encoder)
LORA_ALPHA=8                                            # the lora alpha (both llm and vision encoder)
SIM_ID=edtok_train
RUN_ID=${MODEL_ID}_${SIM_ID}_lora-${USE_LORA}_qlora-${Q_LORA}     # a custom run id that determines the checkpoint folder and wandb run name

DS_STAGE=zero3                                          # deepspeed stage; < zero2 | zero3 >
PER_DEVICE_BATCH_SIZE=2                                 # batch size per GPU
GRAD_ACCUM=1                                            # gradient accumulation steps
NUM_EPOCHS=5                                            # number of training epochs

LR=2e-5                                                 # learning rate
MODEL_MAX_LEN=8192                                      # maximum input length of the model


torchrun $DISTRIBUTED_ARGS train.py \
    --model_id $MODEL_ID \
    --data_path $TRAIN_DATA_PATH \
    --eval_data_path $EVAL_DATA_PATH \
    --image_folder $IMAGE_FOLDER \
    --video_folder $VIDEO_FOLDER \
    --num_frames $NUM_FRAMES \
    --output_dir /dev/shm/kshitijv/checkpoints/$RUN_ID \
    --report_to wandb \
    --run_name $RUN_ID \
    --deepspeed ./ds_configs/${DS_STAGE}.json \
    --bf16 True \
    --num_train_epochs $NUM_EPOCHS \
    --per_device_train_batch_size $PER_DEVICE_BATCH_SIZE \
    --per_device_eval_batch_size $PER_DEVICE_BATCH_SIZE \
    --gradient_accumulation_steps $GRAD_ACCUM \
    --eval_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 1 \
    --learning_rate ${LR} \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length $MODEL_MAX_LEN \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --train_vision_encoder $TRAIN_VISION_ENCODER \
    --use_vision_lora $USE_VISION_LORA \
    --train_vision_projector $TRAIN_VISION_PROJECTOR \
    --use_lora $USE_LORA \
    --q_lora $Q_LORA \
    --lora_r $LORA_R \
    --lora_alpha $LORA_ALPHA
    

```

Terminal Output
```
(lmms-finetune) kshitijv@test:~/lmms$ ./edtok_train_script.sh 
wandb: Appending key for api.wandb.ai to your netrc file: /home/kshitijv/.netrc
W1128 15:30:33.878000 3156557 site-packages/torch/distributed/run.py:793] 
W1128 15:30:33.878000 3156557 site-packages/torch/distributed/run.py:793] *****************************************
W1128 15:30:33.878000 3156557 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1128 15:30:33.878000 3156557 site-packages/torch/distributed/run.py:793] *****************************************
2024-11-28 15:30:35.849306: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-28 15:30:35.850052: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-28 15:30:35.850136: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-28 15:30:35.852876: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-28 15:30:35.860928: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-28 15:30:35.862096: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-28 15:30:35.862100: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-28 15:30:35.863939: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1732836635.873213 3156627 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1732836635.874412 3156624 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1732836635.874420 3156626 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1732836635.876093 3156625 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1732836635.876989 3156627 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
E0000 00:00:1732836635.878219 3156624 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
E0000 00:00:1732836635.878223 3156626 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
E0000 00:00:1732836635.879827 3156625 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-28 15:30:35.891619: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-28 15:30:35.893114: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-28 15:30:35.893114: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-28 15:30:35.893933: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/deepspeed.py:24: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/deepspeed.py:24: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/deepspeed.py:24: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/deepspeed.py:24: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-11-28 15:30:40,904] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
[2024-11-28 15:30:41,202] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-11-28 15:30:41,236] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-11-28 15:30:41,241] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.5
 [WARNING]  using untested triton version (3.1.0), only 1.0.0 is known to be compatible
/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:49: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, weight, bias=None):
/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:67: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):
[2024-11-28 15:30:41,550] [INFO] [comm.py:637:init_distributed] cdb=None
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.5
 [WARNING]  using untested triton version (3.1.0), only 1.0.0 is known to be compatible
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.5
 [WARNING]  using untested triton version (3.1.0), only 1.0.0 is known to be compatible
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.5
 [WARNING]  using untested triton version (3.1.0), only 1.0.0 is known to be compatible
/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:49: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, weight, bias=None):
/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:67: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):
/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:49: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, weight, bias=None):
/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:67: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):
/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:49: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input, weight, bias=None):
/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:67: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_output):
[2024-11-28 15:30:41,920] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-11-28 15:30:41,933] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-11-28 15:30:41,937] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-11-28 15:30:41,937] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Loading model, tokenizer, processor...
[2024-11-28 15:30:47,525] [INFO] [partition_parameters.py:345:__exit__] finished initializing model - num_params = 687, num_elems = 7.06B
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.97it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.96it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.93it/s]
Loading checkpoint shards:  67%|██████████████████████████████████████████▋                     | 2/3 [00:02<00:01,  1.04s/it]Some kwargs in processor config are unused and will not have any effect: num_additional_image_tokens. 
Some kwargs in processor config are unused and will not have any effect: num_additional_image_tokens. 
Some kwargs in processor config are unused and will not have any effect: num_additional_image_tokens. 
WARNING: BNB_CUDA_VERSION=124 environment variable detected; loading libbitsandbytes_cuda124.so.
This can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64

WARNING: BNB_CUDA_VERSION=124 environment variable detected; loading libbitsandbytes_cuda124.so.
This can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64

WARNING: BNB_CUDA_VERSION=124 environment variable detected; loading libbitsandbytes_cuda124.so.
This can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64

Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.02it/s]
Some kwargs in processor config are unused and will not have any effect: num_additional_image_tokens. 
Other multimodal component is freezed... including:
	image_newline
	vision_resampler
LoRA for vision encoder enabled...
LLM will be fully trained...
Vision projector will be fully trained...
WARNING: BNB_CUDA_VERSION=124 environment variable detected; loading libbitsandbytes_cuda124.so.
This can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64

Trainable parameters:
	<truncated due to github issues limit>
	base_model.model.language_model.modules_to_save.default.lm_head.weight
Loading data...
Parameter Offload: Total persistent parameters: 4416512 in 668 params
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: lolmachine27. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.7
wandb: Run data is saved locally in /home/kshitijv/lmms/lmms-finetune/wandb/run-20241128_153058-usju4ps4
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run llava-next-video-7b_edtok_train_lora-False_qlora-False
wandb: ⭐️ View project at https://wandb.ai/lolmachine27/lmms-ft
wandb: 🚀 View run at https://wandb.ai/lolmachine27/lmms-ft/runs/usju4ps4
  0%|                                                                                                 | 0/155 [00:00<?, ?it/s][rank2]: Traceback (most recent call last):
[rank2]:   File "/home/kshitijv/lmms/lmms-finetune/train.py", line 201, in <module>
[rank2]:     train()
[rank2]:   File "/home/kshitijv/lmms/lmms-finetune/train.py", line 194, in train
[rank2]:     trainer.train()
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2052, in train
[rank2]:     return inner_training_loop(
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2388, in _inner_training_loop
[rank2]:     tr_loss_step = self.training_step(model, inputs)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 3485, in training_step
[rank2]:     loss = self.compute_loss(model, inputs)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 3532, in compute_loss
[rank2]:     outputs = model(**inputs)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank2]:     ret_val = func(*args, **kwargs)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
[rank2]:     loss = self.module(*inputs, **kwargs)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank2]:     return inner()
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank2]:     result = forward_call(*args, **kwargs)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/peft/peft_model.py", line 1644, in forward
[rank2]:     return self.base_model(
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank2]:     return inner()
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank2]:     result = forward_call(*args, **kwargs)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 197, in forward
[rank2]:     return self.model.forward(*args, **kwargs)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/models/llava_next_video/modeling_llava_next_video.py", line 889, in forward
[rank2]:     inputs_embeds = self.get_input_embeddings()(input_ids)
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/models/llava_next_video/modeling_llava_next_video.py", line 431, in get_input_embeddings
[rank2]:     return self.language_model.get_input_embeddings()
[rank2]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank2]:     raise AttributeError(
[rank2]: AttributeError: 'ModulesToSaveWrapper' object has no attribute 'get_input_embeddings'
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/kshitijv/lmms/lmms-finetune/train.py", line 201, in <module>
[rank1]:     train()
[rank1]:   File "/home/kshitijv/lmms/lmms-finetune/train.py", line 194, in train
[rank1]:     trainer.train()
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2052, in train
[rank1]:     return inner_training_loop(
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2388, in _inner_training_loop
[rank1]:     tr_loss_step = self.training_step(model, inputs)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 3485, in training_step
[rank1]:     loss = self.compute_loss(model, inputs)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 3532, in compute_loss
[rank1]:     outputs = model(**inputs)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank1]:     ret_val = func(*args, **kwargs)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
[rank1]:     loss = self.module(*inputs, **kwargs)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank1]:     return inner()
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank1]:     result = forward_call(*args, **kwargs)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/peft/peft_model.py", line 1644, in forward
[rank1]:     return self.base_model(
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
[rank1]:     return inner()
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1790, in inner
[rank1]:     result = forward_call(*args, **kwargs)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 197, in forward
[rank1]:     return self.model.forward(*args, **kwargs)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/models/llava_next_video/modeling_llava_next_video.py", line 889, in forward
[rank1]:     inputs_embeds = self.get_input_embeddings()(input_ids)
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/models/llava_next_video/modeling_llava_next_video.py", line 431, in get_input_embeddings
[rank1]:     return self.language_model.get_input_embeddings()
[rank1]:   File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank1]:     raise AttributeError(
[rank1]: AttributeError: 'ModulesToSaveWrapper' object has no attribute 'get_input_embeddings'
W1128 15:31:05.474000 3156557 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3156624 closing signal SIGTERM
W1128 15:31:05.475000 3156557 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3156625 closing signal SIGTERM
W1128 15:31:05.476000 3156557 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3156627 closing signal SIGTERM
E1128 15:31:06.063000 3156557 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 2 (pid: 3156626) of binary: /home/kshitijv/miniconda3/envs/lmms-finetune/bin/python
Traceback (most recent call last):
  File "/home/kshitijv/miniconda3/envs/lmms-finetune/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kshitijv/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-28_15:31:05
  host      : test
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3156626)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by Kshitijpawar** [comment]
setting `USE_VISION_LORA=False` solved it
