### ISSUE TITLE
Phi-3-Vision训练出错

### ISSUE THREAD

**Issue by yjmpepe** [zjysteven/lmms-finetune#9]
1、下载了Phi-3-Vision数据
2、设置example_image.sh中的参数PER_DEVICE_BATCH_SIZE=1，NUM_EPOCHS=5，训练集选择了celeba_image_train.json中的87条，测试集选择celeba_image_eval.json，训练的时候到87步出错：
 20%|█████████████████████████████▊                                                                                                                       | 87/435 [01:45Traceback (most recent call last):
  File "/root/autodl-tmp/lmms-finetune/train.py", line 258, in <module>
    train()
  File "/root/autodl-tmp/lmms-finetune/train.py", line 244, in train
    trainer.train()
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2376, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2804, in _maybe_log_save_evaluate
    metrics = self._evaluate(trial, ignore_keys_for_eval)
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2761, in _evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 3666, in evaluate
    output = eval_loop(
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 3857, in evaluation_loop
    losses, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 4075, in prediction_step
    loss, outputs = self.compute_loss(model, inputs, return_outputs=True)
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 3363, in compute_loss
    outputs = model(**inputs)
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1603, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/peft/peft_model.py", line 1577, in forward
    return self.base_model(
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1603, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 188, in forward
    return self.model.forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Phi-3-vision-128k-instruct/modeling_phi3_v.py", line 1301, in forward
    outputs = self.model(
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1603, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Phi-3-vision-128k-instruct/modeling_phi3_v.py", line 1136, in forward
    raise ValueError(
ValueError: You are attempting to perform batched generation with padding_side='right' this may lead to unexpected behaviour for Flash Attention version of Phi3. Make suizer.padding_side  = 'left'` before tokenizing the input.
3、.sh中去掉--eval_data_path $EVAL_DATA_PATH会提示缺测试集路径，在train.py中设置eval_dataset=None也是同样错误提示。

请问是phi在测试集格式方面有什么要求吗？

**Comment by zjysteven** [comment]
2的问题error message解释了，是phi3独有的问题。我也会建议去掉eval set，3的问题刚刚push了一个fix，用最新的代码再试一下。之前bash script里hard code了eval_strategy是"epoch"，trainer就会去找eval set。现在train.py里加了一行当eval set为空时把eval_strategy改成no不做eval就可以了。https://github.com/zjysteven/lmms-finetune/blob/f4ddd9d4106b40f3e5beecb5f8f4c956b746c578/train.py#L215-L216

**Comment by yjmpepe** [comment]
可以了，多谢！
